variables:
  DOCKER_VERSION:
    value: 20.10.16
  # explicit tag to be used within pipeline
  BUILD_IMAGE_NAME: 
    value: "$CI_REGISTRY_IMAGE/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
    description: "current pipeline image"

  IMAGE_PREVIOUS: 
    value: "${CI_REGISTRY}/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
    description: "previous pipeline image"
  DOCKERFILE_DIR:
    value: "./"
  DOCKERFILE_PATH:
    value: "./Dockerfile"
  DOCKER_COMPOSEFILE_PATH:
    value: "./docker-compose.yml"
  # we also publish a floating tag to simplify manual testing
  BUILD_IMAGE_NAME_LATEST: 
    value: "${CI_REGISTRY_USER_STAG}/cms-ibp" #image build for dockerhub
    description: "latest pipeline image"

  # NAMESPACE:
  #   value: "..."
  SERVICE:
    value: "ibp_cms"

stages:
  - cache
  - prepare-build
  - build
  - deploy

include:
  - project: "devops903408/gitlab/gitlab-ci-template"
    ref: main
    file:
      - "/ci/nodejs/update-cache-yarn.gitlab-ci.yml"
      - "/ci/nodejs/prepare-build.gitlab-ci.yml"
      - "/ci/docker/build-image.gitlab-ci.yml"
      - "/cd/docker/docker-swarm.gitlab-ci.yml"
