version: '3.7'

services:
  cms_ibp:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: 
    ports:
      - 3000:80
    deploy:
      placement:
        # constraints:
        #   # - "node.hostname==CacheNode-3-215"
        #   - "node.labels.redisCluster == true"
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M