/**
 * @description Languages
 */
 export default [
    { id: 'ar', name: 'Arabic' },
    { id: 'awa', name: 'Awadhi' },
    { id: 'az', name: 'Azerbaijan' },
    { id: 'bh', name: 'Bihari' },
    { id: 'bn', name: 'Bengali' },
    { id: 'de', name: 'German' },
    { id: 'en', name: 'English' },
    { id: 'en-gb', name: 'English (UK)' },
    { id: 'en-us', name: 'English (US)' },
    { id: 'es', name: 'Spanish' },
    { id: 'es-es', name: 'Spanish (EU)' },
    { id: 'fa', name: 'Persian' },
    { id: 'fr', name: 'French' },
    { id: 'fr-ca', name: 'French' },
    { id: 'gu', name: 'Gujarat' },
    { id: 'ha', name: 'Hausa' },
    { id: 'hi', name: 'Hindi' },
    { id: 'it', name: 'Italian' },
    { id: 'ja-latn', name: 'Japanese (Romaji)' },
    { id: 'ja', name: 'Japanese' },
    { id: 'jv', name: 'Javanese' },
    { id: 'kn', name: 'Kannada' },
    { id: 'ko', name: 'Korean' },
    { id: 'ko-latn', name: 'Korean (Romaja)' },
    { id: 'ko-hang', name: 'Hangul (Hangeul)' },
    { id: 'mai', name: 'Maithili' },
    { id: 'ml', name: 'Malayalam' },
    { id: 'mr', name: 'Marathi' },
    { id: 'my', name: 'Burmese' },
    { id: 'or', name: 'Oriya' },
    { id: 'pa', name: 'Punjabi' },
    { id: 'pl', name: 'Polish' },
    { id: 'pt', name: 'Portuguese' },
    { id: 'ro', name: 'Romanian' },
    { id: 'ru', name: 'Russian' },
    { id: 'sd', name: 'Sindhi' },
    { id: 'su', name: 'Sundanese' },
    { id: 'ta', name: 'Tamil' },
    { id: 'te', name: 'Telugu' },
    { id: 'th', name: 'Thai' },
    { id: 'tr', name: 'Turkish' },
    { id: 'uk', name: 'Ukrainian' },
    { id: 'ur', name: 'Urdu' },
    { id: 'vi', name: 'Vietnamese' },
    { id: 'yo', name: 'Yoruba' },
    { id: 'zh-cjy', name: 'Jin Chinese' },
    { id: 'zh-cmn', name: 'Mandarin Chinese' },
    { id: 'zh-gan', name: 'Gan Chinese' },
    { id: 'zh-hak', name: 'Hakka Chinese' },
    { id: 'zh-hsn', name: 'Xiang Chinese' },
    { id: 'zh-nan', name: 'Min Nan Chinese' },
    { id: 'zh-wuu', name: 'Wu Chinese' },
    { id: 'zh-yue', name: 'Yue Chinese (Cantonese)' },
    { id: 'zh-hans', name: 'Tiếng Trung (giản thể)' },
    { id: 'zh-hant', name: 'Tiếng Trung (phồn thể)' },
    { id: 'zh-latn-pinyin', name: 'Tiếng Trung (Pinyin)' },
    { id: 'zh-latn-wadegile', name: 'Tiếng Trung (Wade-Giles)' }
]
